default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  user: postgres
  password: postgres
  database: railsapijwt_development
  host: localhost
  port: 5432
test:
  <<: *default
  user: postgres
  password: postgres
  database: railsapijwt_test
  host: localhost
  port: 5432
staging:
  <<: *default
  database: railsapijwt
  username: railsapijwt
  password: <%= ENV['RAILSAPIJWT_DATABASE_PASSWORD'] %>
production:
  <<: *default
  database: railsapijwt
  username: railsapijwt
  password: <%= ENV['RAILSAPIJWT_DATABASE_PASSWORD'] %>
